### ISSUE TITLE
It occured some problem using Samsung SPC-4200P Bios

### ISSUE THREAD

**Issue by win3200** [OBattler/86Box#100]
at first, Thank you for your help
VERY!! VERY!!! :)

recently, I launched 86box, and checked some modified function with SPC-4200P Bios

Samsung Aladdin 286 bios SPC-4200P
turn on 86box using SPC-4200P bios.
"keyboard stuck..." message occured with BEEP

when I pressed keyboard alt+tab to change windows, in 86box many tab key event is occured.

on Hercules with GREEN/AMBOR/WHITE
I changed color GREEN in Hercules Graphic Mode, I launched the Game as example : Lost Ducth Man :)
game screen was chaning original color WHITE....
but exit game....screen color was GREEN...

after I launched SIMCGA.COM in Hercules Mode
some program was freezing...example...Norton Commander...

and When I used Turbo C++ for DOS, it shows "dpmi server initialization error - machine not in database"

Plz...I want to your help.
and thank you for your help...everytime

**Comment by MoochMcGee** [comment]
i can't believe this is the 100th issue. jesus christ.

**Comment by win3200** [comment]
Hi  MoochMcGee
Why are you looking for the jesus?
Is it a big mistake I asked?
So What do you like to post here?

**Comment by MoochMcGee** [comment]
@win3200 I'm not??? God damn, your English is fucking terrible.

**Comment by win3200** [comment]
Ok.

It is not an English speaking country.
But
Your reply is mother fucking terrible, too :)
If God exists, I pray that your descendants will have a curse. :)
Thanks~


________________________________
보낸 사람: Melissa Goad <notifications@github.com>
보낸 날짜: 2017년 4월 23일 일요일 오전 4:06
받는 사람: OBattler/86Box
참조: win3200; Mention
제목: Re: [OBattler/86Box] It occured some problem using Samsung SPC-4200P Bios (#100)


@win3200<https://github.com/win3200> I'm not??? God damn, your English is fucking terrible.

**Comment by OBattler** [comment]
- win3200: I apologize for MoochMcGee's attitude. He has already been reprimanded for this incident and I will make sure it does not repeat.

As for your bug reports, I am going to look into them.

**Comment by MoochMcGee** [comment]
*she

Also, how are we supposed to look into an issue if it's in such bad English that nobody can understand them?

**Comment by dhrdlicka** [comment]
@MoochMcGee that doesn't mean it's not rude to treat the reporter like you have.

**Comment by win3200** [comment]
@MoochMcGee // 
I think it is wrong that I came here.
I'm ashamed that someone like you is living with me.
Does your children know that a person like you is a parent if you are parent?
It is rude and rude, and human quality itself is bottom ....
I do not know if Google translator translated well...
If this was not my English but my country, I would not have treated you like you.
I will not discuss issues or issues in the future.

As I said above, I wish God existed in such a time.
And I hope God will speak my country.
And someday you stand before him
I hope he can not hear you.
I hope there is no forgiveness of God  :(

**Comment by OBattler** [comment]
Just ignore MoochMcGee, he's not  person in the position of authority here. I am (I am the main developer). I just deleted their last rude post. I apologize to you for what he did.

**Comment by win3200** [comment]
OBattler //  I'm afraid I've been involved in this good site anyway.
I will try to make English sentences as good as possible with Google Translator.
I am a beginner developer using C/C++/Python/SML and  want to study the source as much as possible.
Thank you very much.
From Friday to Sunday you will be fortunate ...

**Comment by MoochMcGee** [comment]
*she
