### ISSUE TITLE
New emulation CDROM no support mix cd data+audio 

### ISSUE THREAD

**Issue by ThingUroboros** [OBattler/86Box#113]
Hi, 
Disk does not load. data is OK, but audio not function.

**Comment by TC1995** [comment]
Use the ioctl one at the moment if you're using Windows as a host.

**Comment by ThingUroboros** [comment]
I use MSDOS 6.22 , but tray win 95 and let me know

**Comment by OBattler** [comment]
He said when using Windows as host, not guest. That is, when running the emulator on top of Windows. And at least the mixed mode CD's I tried work fine when mounted as CUE/BIN... need to try as IOCTL again.

**Comment by OBattler** [comment]
You might be using an outdated build of 86Box. I know there were CD audio issues at some point when using host drives, but I fixed them.
If that still doesn't work, tell me exactly what CD are you trying to load and whether it is using a host drive (and if yes, what kind - physical IDE, physical SATA, Daemon Tools IDE, Daemon Tools SCSI, Alcohol 120%, etc.) or a CUE/BIN image.

**Comment by ThingUroboros** [comment]
In win 95 it is functional.
In win 98 crash 86box.

In win 95
Mount virtual cdrom daemon tools OK
Cue image bin + audio cue mixed OK

MSDOS 6.22
Mount virtual cdrom daemon tools - KO
Cue image bin + mixed audio cue - KO

**Comment by ThingUroboros** [comment]
This firt vesion have problem with ide cdrom mixed data audio.
Version 1.20
f6ef1f83

Last version 1.10 it is OK 
Td07d539

**Comment by TC1995** [comment]
Try the latest git commit, I've verified it works fine in both buses (SCSI and IDE).

**Comment by ThingUroboros** [comment]
Which driver do you use for SCSI a tray AHA-1540/1542/1640 APSI MANAGer for DOS Version 3.36 
ASPI4DOS.SYS instalation failed

**Comment by TC1995** [comment]
ASPI 3.35 or lower.

**Comment by OBattler** [comment]
What IDE/ATAPI CD-ROM driver for DOS are you using? A lot of the drivers use vendor-specific commands to play audio, and might therefore not work. I recommend either OAKCDROM.SYS or VIDE-CDD.SYS.

**Comment by ThingUroboros** [comment]
Hi a USED for AHA-1542CF

OK configuration for me
Config in 86box v.120
Address 0x130
IRQ 10
DMA 6
uncheck Enable BIOS 
BIOS Address C800H

Configuration for  DOS 
ASPI4_30.ZIP - 106.2 kb - 07-31-96

autoexec.bat
LH C:\CDROM\MSCDEX.EXE /D:ASPICD0
config.sys
DEVICE=C:\AFDISK\ASPI4DOS.SYS /P130
DEVICE=C:\AFDISK\ASPICD.SYS /D:ASPICD0

Now a tray OAKCDROM:SYS or VIDE-CDD.SYS

**Comment by OBattler** [comment]
Could you please upload the CD-ROM image you are trying to load to Mega so I can try to load it myself and see where it goes wrong?

**Comment by ThingUroboros** [comment]
Wait pls i uploading files on the server.

http://fixcode.eu/test.cue

**Comment by OBattler** [comment]
With the latest 86Box, I can play the audio tracks without problems using Sony's CD Player, also using ATAPI.

**Comment by ThingUroboros** [comment]
I'm sorry it's great that it works in the Sony player, but in the game I tried it through the player that is in Dos Navigator and there it does not work either. The game has mix data+audio detection and it does not work in earlier emulation. Yes in SCSI it also works.

**Comment by OBattler** [comment]
Try the latest 86Box, I fixed a bug that was preventing most things of setting that the emulated CD-ROM drive is audio-capable, I tested your game and it seems to work now.

**Comment by ThingUroboros** [comment]
Nice work. It is true. 
ATAPI PIO now OK

ATAPI PIO and DMA -> Bios no detect CDROM

**Comment by OBattler** [comment]
I'll look into that.

**Comment by OBattler** [comment]
OK, I just fixed that. ATAPI PIO and DMA CD-ROM's should now be detected correctly.

**Comment by ThingUroboros** [comment]
Yes, everything is working now
