### ISSUE TITLE
Audio tracks can not hear sound in CDROM

### ISSUE THREAD

**Issue by ThingUroboros** [OBattler/86Box#117]
Version c669a05 tested.
Dos navigator detects a sound track, but not playing time remains 0:00
PROBLEM IN PIO , PIO + DMA, SCSI.

**Comment by OBattler** [comment]
What version of DOS Navigator?

**Comment by OBattler** [comment]
Left (or right) click the CD-ROM icon on the status bar, and make sure Mute is not ticked.

**Comment by ThingUroboros** [comment]
Sorry
