### ISSUE TITLE
Adding Bochs bios for wider distribution

### ISSUE THREAD

**Issue by ghost** [OBattler/86Box#120]
The Bochs bios rom seems to have a licensing scheme which may allow bundling of 86Box with the rom. This would also allow the developers here to modify the bios for emulation enhancements. Is this currently being considered? However, I don't know whether the two licenses are compatible with commercial distribution, too, although some versions of the GPL license allows this.

Also, along these lines, is it possible to create a branch of 86Box with enhanced portability to other host operating systems, such as FreeBSD? This would require a focus on a single model type, but would remove the necessity of the dialog boxes and dependency on the external windows. Also, the GUI and sound/video/input interfaces may be made generic for simple replacement to the equivalent functions of another host OS. For the current win32 systems, it should be possible to remove the dinput and d3d dependencies. All the video code could be contained in a single file, for instance.

**Comment by TC1995** [comment]
For the bochs bios, I think no.

**Comment by en-passant-2001** [comment]
Bochs bios: http://bochs.sourceforge.net/cgi-bin/lxr/source/bios/rombios32.c
```
//  32 bit Bochs BIOS init code
//  Copyright (C) 2006 Fabrice Bellard
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2 of the License, or (at your option) any later version.
```
And from the Bochs bios makefile (files seem to have same license as above):
```
BIOS-bochs-latest: rombios16.bin rombios32.bin
         cat rombios32.bin rombios16.bin > $@

rombios32.bin: rombios32.out rombios.h

rombios32.out: rombios32start.o rombios32.o rombios32.ld

rombios32.bin: rombios32.out rombios.h

rombios16.bin: rombios.c apmbios.S biossums rombios.h
```
From the Bochs bios help page:
```
the BIOS image (usually called BIOS-bochs-latest)

```

**Comment by waltje** [comment]
I have almost finished generalizing the main code tree, and splitting off the platform- and UI-dependent parts into submodules. A Linux version using Wx runs fine now, BSD testing will follow soon.

The BOCHS idea... dunno, will bring this up [again].

**Comment by OBattler** [comment]
After a discussion in the IRC channel, we have determined this is not going to work as the Bochs BIOS requires to have all the devices pre-initialized while real BIOS'es require them to *NOT* be pre-initialized, so they would conflict. Therefore, I am closing this issue.
