### ISSUE TITLE
MegaPC 386DX BIOS password? 

### ISSUE THREAD

**Issue by startmenu** [OBattler/86Box#121]
There isn't a nvr for that machine so it is created automatically once it runs. But when enter the BIOS setup, I'm asked a passwork while I've no idea what it is. 
Is there a initial password or a cracked nvr file available?

**Comment by OBattler** [comment]
There is a NVR for this machine in the repo, use it.

**Comment by OBattler** [comment]
Actually, it's for the other MegaPC, but the NVR's are identical - just copy megapc.nvr to megapcdx.nvr .

**Comment by dhrdlicka** [comment]
Honestly the 86box distribution should include the NVR files to prevent such problems happening in the future.

**Comment by telanus** [comment]
> Actually, it's for the other MegaPC, but the NVR's are identical - just copy megapc.nvr to megapcdx.nvr .



> There is a NVR for this machine in the repo, use it.
Is this still available in the repo? I had a look but couldn't find it

**Comment by johansenmeister** [comment]
Hi! 
Has anyone got a link for the NVR file?

**Comment by Korkman** [comment]
I found it in https://github.com/libretro/libretro-pcem/blob/master/megapc.nvr
