### ISSUE TITLE
New problems 

### ISSUE THREAD

**Issue by ThingUroboros** [OBattler/86Box#124]
Hi, new version 2.0 044e3ba some problems.

1.I tested  game Spellcross
The 86box will hang up after a while. Statistics are changing. But the mouse is stuck picture is standing.
2. CDROM mount iso not function play audio tracks.
Check or uncheck "mute" - not function

I'd like to help. How to use debug mod and where to see the listing?

I compiled last version 

DEBUG	= y
OPTIM	= n
COPTIM	= -O1

**Comment by TC1995** [comment]
for some reason, bin/cue image mounting does not play audio, but through ioctl it does, and microsoft serial mouse works here, you just need the mouse.com DOS driver to initialize the ms serial mouse.

**Comment by OBattler** [comment]
I fixed CUE/BIN audio, see if that also fixes the other problem.

**Comment by ThingUroboros** [comment]
Last version 6a345aa804d21ced5b073d6f106af8ffea72cac6 is OK it is better sound super.
