### ISSUE TITLE
CDROM image path with unicode characters

### ISSUE THREAD

**Issue by zestybaby** [OBattler/86Box#126]
I was trying to load CD image with Chinese characters in path, but it fails to load which acts like nothing happened. It can be fixed by renaming folders to not containing unicode characters, which leads me to guess that this project currently still lacks proper unicode support. So my question is, will we get unicode support in path eventually?

**Comment by OBattler** [comment]
The problem is, the image mounting code comes from DOSBox which uses C++ iostreams which on Windows are not Unicode-aware. Eventually I plan to convert it to use C _wfopen, but it will take a while.

**Comment by waltje** [comment]
86Box is completely Unicode now, paths are fine now.
