### ISSUE TITLE
some MPU-401 issues

### ISSUE THREAD

**Issue by basic2004** [OBattler/86Box#129]
I tested about standalone MPU-401, and SB16's MPU-401, with rev#793.
and I found some issues.

1. Standalone MPU-401 checkbox save problem
Standalone MPU-401 turned to uncheck after quit and restart 86Box.

2. Standalone MPU-401 can execute with another soundcard
I tested after change soundcard to Windows Sound System, MPU-401 worked.
Is this bug? What's model name of this MPU-401 interface card? I don't know. but...

I saw an ability of really standalone MPU-401.
I think it will can work with any soundcard, maybe.
(with SB16/AWE32 too, if standalone MPU-401's base address not same with SB16's MPU-401.)
and, this can separate MIDI out device between standalone MPU-401 and SB... (or use same device)

for example...
SB16's MIDI base address : 300 (UART)
SB16's MIDI out device : MIDI Port A
standalone MPU-401 base address : 330
standalone MPU-401 IRQ : 9 (Intelligent)
standalone MPU-401 MIDI out device : MIDI Port B

3. Problem with SB16/AWE32's MPU-401 UART mode
SB16's MPU-401 Intelligent mode, and SBMIDI works well.
but UART mode didn't work well.

This started to port by TC1995, I know porting from DOSBox. Thanks to him.
but PCem's SB16 UART mode was right.

I tested two DOS MIDI player, MEGAMID and DOSMID.
and add argument /mpu when run these with midi file.

MEGAMID can't detect MPU-401 with DOSBox and current 86Box, but PCem did.
DOSMID can detect and play MPU-401 with all.

I asked who had real machines and SB16/AWE32.
They told me MIDI plays OK both MEGAMID and DOSMID.
Can revert back for MPU-401 UART mode's?

Thanks!

**Comment by basic2004** [comment]
I used SoftMPU from MPU-401 UART mode in PCem and 86Box before porting,
softmpu.exe /mpu:330 /sb:220 /irq:5 (I didn't use /sbmidi for MPU-401 output)

It didn't work in current version of 86Box, too.
Intelligent mode doesn't need SoftMPU :)

**Comment by OBattler** [comment]
Right now, you can't have two MPU-401's at the same time because there is only a single interface to host MIDI device.
For UART mode, you need to specifically set the MPU-401 into UART mode in settings.

> Standalone MPU-401 checkbox save problem
Will look into this.

> Standalone MPU-401 can execute with another soundcard
That's the whole point. It's for using MPU-401 with sound cards that don't already provide their own.

**Comment by OBattler** [comment]
Also, I'll try SoftMPU and see what happens.

**Comment by OBattler** [comment]
> MEGAMID can't detect MPU-401 with DOSBox and current 86Box, but PCem did.
Now MEGAMID works on 86Box again, after I made the MPU-401's RESET command send an ACK even when in UART mode.
SoftMPU now detects the MPU-401 fine, but when I run Princess Maker 2 (English version), I hear nothing, but then again I don't know the exact parameters I need to run SoftMPU with for that game or what I need to set Princess Maker 2 to.

**Comment by basic2004** [comment]
Oh, thanks! This worked both, Intelligent, UART mode in current rev(#797).
UART mode didn't play Princess Maker 2 with SoftMPU, it was PCem's spec.
but SoftMPU and MEGAMID turned back to enable.
also Intelligen mode works all.

I tested

- MEGAMID, DOSMID
- SoftMPU
- Princess Maker 2, Hardball 3, The Lost Vikings

so UART issues solved now.
But I found some issues.

1. MIDI stopped accidently when playing long time.
I played 'The Lost Vikings' with MuntVsti, and SB16's MPU-401 Intelligent mode.
but the music stops accidently... sometimes this plays too delayed (about 10sec?)
what's this issue? overflow? or delayed and stacked signal?

2. MIDI Out list selection was grayed yet when standalone MPU-401 checked.
(MIDI Out to be selectable when went other settings and back to Sound settings)
This should selectable with selected SB series or checking standalone MPU-401.
and MIDI Out going gray out when selected non SB card and uncheck standalone MPU-401.

**Comment by OBattler** [comment]
> MIDI stopped accidently when playing long time.
I suspect these kind of issues are due to the emulation not always being at 100%, and that's unfortunately a CPU emulation issue that only Sarah can fix.

> MIDI Out list selection was grayed yet when standalone MPU-401 checked.
I'll fix that.

**Comment by OBattler** [comment]
I just fixed that. Now checking the standalone MPU-401 check box will also enable the MIDI OUT device selection box.

**Comment by basic2004** [comment]
I tested again, same MIDI environment.
It didn't happen again, Intelligent mode, UART+SoftMPU, SBMIDI+SoftMPU...

I changing MIDI playback environment now.
I guess this VSTHost's setting problem, ASIO4ALL...

If this issues appear again, I'll report here.

**Comment by basic2004** [comment]
MIDI signal delayed again, I tested with 'The Lost Vikings'.
Delaying about 2-3 seconds when I set SB16, Intelligent MPU-401 mode.
Changed UART mode and reboot, this problem didn't appear.

**Comment by basic2004** [comment]
Finally, I found delaying problem.
This was VSTi problem, I using Munt MT-32 emulator VSTi 2.1.
Munt VSTi is here http://falcosoft.hu/softwares.html#munt_vsti

MIDI delaying appeared on 86Box Intelligent MIDI, UART MIDI too. and PCem's UART MIDI too.
Delaying appeared when I testing with 'The Lost Vikings'.

I found wxWidgets+mt32emu branch, it ported 86Box's Intelligent MIDI.
Compiled it and tested Intelligent MIDI, I didn't hear delaying.

**Comment by basic2004** [comment]
Thanks to support Munt MT-32 emulation.
Downloaded last version and tested 2 hours more, I felt no more delaying issue from 86Box.

But Munt emulation isn't latest version.
If you port current version of mt32emu branch, MT-32 Message and Instruments appear from Status window.

All right, I'll close this issue.

**Comment by OBattler** [comment]
I'm going to look into that but it's going to take a while since the status window as it is right now needs to be redone first.

**Comment by OBattler** [comment]
Looking at the Sound Blaster 16 code in the Windows NT 3.5 DDK, it seems that the Sound Blaster 16's MPU-401 starts out in intelligent mode, with IRQ wired to the Sound Blaster 16 IRQ, with the CT mixer's IRQ source register reflecting the IRQ pending status in bit 2.
NT 3.5 actually relies on this - it sends command 3F (set UART mode) and then waits for the IRQ and on recept of the IRQ, it reads the IRQ source register to make sure the IRQ comes from the MPU-401.
It would be actually interesting to try something that relies on intelligent mode (Princess Maker 2?) on the real Sound Blaster 16 with MPU-401 IRQ set to the same IRQ as the sound card, maybe it would work. A Vogons thread implies the CT-1750's MPU-401 could work in intelligent mode, so maybe so can CT-1745.
MEGAMID's behavior sheds further light on this - if it's true that the RESET command does not ACK in UART mode, then MEGAMID expecting the ACK would mean it actually expects the MPU-401 to start in UART mode, but I'm not sure. It does seem like there's more to the Sound Blaster 16's MPU-401 than is officially documented, but I guess probing the real card would be needed to understand everything.
