### ISSUE TITLE
MCA PS/2 are broken

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#130]
Tested with r805 : black screen at start even with VGA only adapter.
Pclog stops here : ps2_read: port=0096 temp=7a
ps2_write: port=0096 val=00 f000:03d8
Tested fine with r749, failed since r750

**Comment by OBattler** [comment]
Are you sure it's 750 that breaks it? That corresponds to this commit:
https://github.com/OBattler/86Box/commit/f416613cfa54a1e50e3a541c09ecc58f6edcc9e2 ,
which does not affect anything PS/2-related at all.

**Comment by OBattler** [comment]
I just tested and I get the same problem on 749. I'm going to bisect now to see exactly which build it's broken from.

**Comment by OBattler** [comment]
740 works but 749 doesn't. Trying 745 next.

**Comment by OBattler** [comment]
748 works but 749 doesn't. So it's 749 that breaks it.

**Comment by Altheos** [comment]
Sorry i tested numerous builds and confirm that it is build 749 that broke ps2.
