### ISSUE TITLE
Need for speed -> GAME problems with keyboard.

### ISSUE THREAD

**Issue by ThingUroboros** [OBattler/86Box#131]
When installing a cdrom game and moving in the menu, the keyboard stops responding as darts and more. The same thing in the menus in the game until only the mouse is used can then get to play the race. But if you want to climb out of the race, "escape" works but enter no. 
It's not the last version I did in all I've ever tried.

This problem is in MSDOS 6.22 testing

**Comment by OBattler** [comment]
See if it also happens on mainline PCem. I know that the AT keyboard controller emulation leaves a lot to be desired right now.

**Comment by ThingUroboros** [comment]
In PCEM v12 keyboard is OK

**Comment by OBattler** [comment]
Then find whatever is difference between our keyboard emulation and the mainline's, and remove the differences one by one until it works.

**Comment by ThingUroboros** [comment]
This is different:
This is different
https://github.com/OBattler/86Box/blob/master/src/keyboard_at.c#L205

void keyboard_at_adddata_keyboard(uint8_t val)
{
	/* Modification by OBattler: Allow for scan code translation. */
	if ((mode & 0x40) && (val == 0xf0) && !(mode & 0x20))
	{
		sc_or = 0x80;
		return;
	}
	/* Skip break code if translated make code has bit 7 set. */
	if ((mode & 0x40) && (sc_or == 0x80) && (nont_to_t[val] & 0x80) && !(mode & 0x20))
	{
		sc_or = 0;
		return;
	}
        key_queue[key_queue_end] = (((mode & 0x40) && !(mode & 0x20)) ? (nont_to_t[val] | sc_or) : val);
        key_queue_end = (key_queue_end + 1) & 0xf;
	if (sc_or == 0x80)  sc_or = 0;
        return;
}

void keyboard_at_adddata_keyboard_raw(uint8_t val)
{
        key_queue[key_queue_end] = val;
        key_queue_end = (key_queue_end + 1) & 0xf;
        return;
}

**Comment by OBattler** [comment]
Check if the latest build of 86Box fixes this.

**Comment by ThingUroboros** [comment]
Yes keyboard is OK

**Comment by OBattler** [comment]
OK, then this issue can be closed.
