### ISSUE TITLE
Missing common coding style

### ISSUE THREAD

**Issue by dhrdlicka** [OBattler/86Box#134]
The project is missing some common style guidelines that all developers abide by.

**Comment by htjywf2008** [comment]
I agredd this.

**Comment by waltje** [comment]
This is, um, being battled out, er, no, worked on ;-)

**Comment by OBattler** [comment]
By now, we've pretty much settled on waltje's coding style, we just need to officially codify it somewhere so that all the people who want to contribute code, know what the style is.
