### ISSUE TITLE
Feature Request: ECS Si54P-AIO Emulation

### ISSUE THREAD

**Issue by PeladoFeo** [OBattler/86Box#135]
I would like to see the Si54P-AIO motherboard from ECS on 86Box,
but seems like something is missing...

**Comment by PeladoFeo** [comment]
Alright! Here's the SIS 5500 chipset documentation.

**Comment by OBattler** [comment]
Where? I see no attachment.

**Comment by PeladoFeo** [comment]
Alright! [Here](http://rl531.bmstu.ru:3000/chipsets/sis/s550Xr200.rar) is the SIS 550x chipset documentation.

**Comment by OBattler** [comment]
Alright, I'll look into it. Please e-mail me a BIOS though.

**Comment by PeladoFeo** [comment]
[Here](http://www.elhvb.com/mobokive/Archive/Ecs%20-%20Elitegroup/bios/si54paio.zip) is a BIOS.

**Comment by OBattler** [comment]
I downloaded the BIOS and edited the post ot remove the link as while I personally have no problem with BIOS distribution, GitHub may be of a different opinion.

**Comment by PeladoFeo** [comment]
I've finally e-mailed you a BIOS.

**Comment by BoisterousSleet75** [comment]
@OBattler Any news for the ECS Si54P-AIO Emulation?

**Comment by PeladoFeo** [comment]
Sorry if I requested ECS Si54P-AIO emulation,
but it's perhaps the early motherboard to be able to boot from CD-ROMs...

**Comment by OBattler** [comment]
I am going to look at this for 86Box v3.0.
