### ISSUE TITLE
How to "mount" floppy on 86box ?

### ISSUE THREAD

**Issue by cedsanzo** [OBattler/86Box#139]
Hi,

First sorry for my poor english. Hope my question will be understanding.
I just install 86box on my computer and download image form MSDOS 6.22.
Someone can tell me how to mount it for 86box boot on it at starting ? 
do I need a specific directory to place image files ?

Thx

Cédric

**Comment by zacchi4k** [comment]
First, *the issue section on GitHub is supposed to be used to post bugs, not general questions about the application and its GUI.*
Second, you have to go to Tools>Settings>Removable devices and enable at least a floppy drive in here, then close the settings window and right click on the floppy icon in the bottom left corner to mount an image.

**Comment by cedsanzo** [comment]
Sorry...
And thank you
