### ISSUE TITLE
Keyboard not working correctly under Windows 9x setup using Tyan Titan-Pro AT/ATX

### ISSUE THREAD

**Issue by zacchi4k** [OBattler/86Box#140]
If you set up 86Box to use a Tyan Titan-Pro AT/Tyan Titan-Pro ATX and proceed to install Windows 95/98/ME, then the keyboard will start to work incorrectly when setup enters the GUI part, since the arrow keys no longer work and Enter starts to act like the Tab key, switching between two (only two) different GUI elements.

**Comment by dhrdlicka** [comment]
Post your configuration file.

Also, I can't reproduce your bug with the following config on 6e5647f477d480e65ba260e0243189fa4eb7a3fc:
```ini
[General]
video_fullscreen_scale = 1
nvr_path = D:\86box\nvr/
force_43 = 1

[Machine]
model = 440fx
mem_size = 131072
cpu_use_dynarec = 1
cpu = 3
cpu_enable_fpu = 1
nvr_path = D:\86box\nvr\

[Video]
gfxcard = virge375
video_speed = 5
voodoo = 1

[Input devices]
mouse_type = intellimouse
joystick_type = 0

[Sound]
opl3_type = nukedopl
sndcard = sbawe32

[Network]
net_type = slirp
net_card = ne2kpci

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 2
texture_memory = 2
render_threads = 2
bilinear = 1
dacfilter = 0
recompiler = 1

[Hard disks]
hdd_01_parameters = 63, 16, 2031, 0, ide_pio_and_dma
hdd_01_fn = G:\Documents\86box HDD\Windows 95.hdi
hdd_01_ide_channel = 0:0

[Removable devices]
fdd_01_fn = C:\Users\rezedus\Documents\Microsoft Windows 1.01 (1985) [English] (5.25'')\media_img\Disk05.img
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 0, atapi_pio_and_dma
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = D:\SW\AW-OS\Microsoft Windows 98 (with Plus! 98) (4.10.1998)\Windows 98 with Plus! 98.iso

[Realtek RTL8029AS]
mac = 66:c4:76
```

**Comment by zacchi4k** [comment]
Here's my config file:

`gameblaster = 0
gus = 0
ssi2001 = 0
voodoo = 0
netinterface = 1
netcard = 1
model = 34
cpu_manufacturer = 0
cpu = 12
cpu_use_dynarec = 1
gfxcard = 11
video_speed = 5
sndcard = 7
cpu_speed = 10
has_fpu = 1
slow_video = 1
cache = 4
cga_composite = 0
disc_a = 
disc_a_writeprot = 0
disc_b = 
disc_b_writeprot = 0
mem_size = 32768
cdrom_drive = 0
cdrom_enabled = 1
cdrom_channel = 2
cdrom_path = 
vid_resize = 0
vid_api = 0
video_fullscreen_scale = 0
video_fullscreen_first = 1
hdc_sectors = 63
hdc_heads = 16
hdc_cylinders = 509
hdc_fn = D:\Zacchi's files\Emulatori\pc\PCem\hdds\MS DOS 6.22.img
hdd_sectors = 0
hdd_heads = 0
hdd_cylinders = 0
hdd_fn = 
hde_sectors = 0
hde_heads = 0
hde_cylinders = 0
hde_fn = 
hdf_sectors = 0
hdf_heads = 0
hdf_cylinders = 0
hdf_fn = 
drive_a_type = 7
drive_b_type = 7
force_43 = 0
enable_overscan = 0
enable_flash = 1
enable_sync = 0
mouse_always_serial = 0
joystick_type = 0
window_w = 0
window_h = 0
window_x = 0
window_y = 0
window_remember = 0
aha154x = 0
scsi_base = 816
scsi_irq = 11
scsi_dma = 6
atapi_cdrom_channel = 2
scsi_cdrom_enabled = 0
scsi_cdrom_id = 3

[Joysticks]
joystick_0_nr = 0
joystick_1_nr = 0

[Machine]
model = tpatx
nvr_path = D:\Zacchi's files\Emulatori\pc\86Box\nvr\
cpu_use_dynarec = 1
cpu = 19
mem_size = 65536
cpu_enable_fpu = 1

[Video]
gfxcard = stealth3d_3000
video_speed = 4

[Input devices]
mouse_type = intellimouse

[CGA]
display_type = 1
composite_type = 1
rgb_type = 0
snow_enabled = 1

[Diamond Stealth 3D 3000 (S3 ViRGE/VX)]
memory = 4
irq = 3
bilinear = 0
dithering = 0

[Realtek RTL8029AS]
mac = d5:94:99

[Sound]
sndcard = sbawe32

[Network]
net_type = slirp
net_card = ne2kpci

[Hard disks]
hdd_01_parameters = 63, 16, 2080, 0, ide_pio_and_dma
hdd_01_fn = D:\Zacchi's files\inesp\Documenti\HDD\Windows ME
hdd_01_ide_channel = 0:0

[Removable devices]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd_dualrpm
cdrom_01_parameters = 1, atapi_pio_and_dma
cdrom_01_ide_channel = 1:0
cdrom_02_parameters = 0, atapi_pio_and_dma
cdrom_02_ide_channel = 1:1
fdd_01_turbo = 1
cdrom_01_host_drive = 200
cdrom_01_image_path = D:\Zacchi's files\ISO\[ITA] Windows 98 SE.iso

[General]
video_fullscreen_scale = 3

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 0
dacfilter = 0
render_threads = 2
recompiler = 1`

**Comment by mw308** [comment]
Using Jenkins number #1320 I can confirm this is still an issue using the Tyan ATX and a Pentium Pro 200.

**Comment by OBattler** [comment]
This has been fixed this month when I reworked the AT keyboard controller emulation.
