### ISSUE TITLE
Frequent crashes when using network card

### ISSUE THREAD

**Issue by adolfintel** [OBattler/86Box#141]
86Box seems to crash a lot when doing network operations, such as downloading a file or accessing smb shares.

Host OS: Windows 10 x64
86Box Version: 2.00 (from your builds)
Guest OS: Windows 98 SE
Host Network card: Atheros Ar81xx
Guest Network card: Novell NE1000 (default settings), Network type SLiRP
Machine: Intel Advanced/ATX, Pentium MMX 233, 256MB memory, S3 ViRGE/DX Fast VLB/PCI, Voodoo 2, Sound Blaster 16 with Nuked OPL, hard disk and cdrom on IDE (PIO+DMA)

According to Windows, the crash is a memory violation, and it's always at the same instruction
```
Faulting application name: 86Box.exe, version: 2.0.0.0, time stamp: 0x00000000
Faulting module name: 86Box.exe, version: 2.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x001b6ac4
Faulting process id: 0x1980
Faulting application start time: 0x01d2ef487911582d
Faulting application path: C:\Users\Federico\Desktop\86box\86Box.exe
Faulting module path: C:\Users\Federico\Desktop\86box\86Box.exe
Report Id: 5e560710-03a0-443a-ac23-c25ae6a825d1
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by adolfintel** [comment]
PCap doesn't seem to be affected though

**Comment by TC1995** [comment]
I think it's really the configuration of NE1000, try using the NE2000 instead.

**Comment by adolfintel** [comment]
It doesn't crash but it doesn't work either. It's detected and the driver installs but then it does nothing.
NE1000 with PCap works fine though, I guess I'll stick with that

**Comment by OBattler** [comment]
For Windows 98 SE, use the Realtek RTL8029AS instead. That works quite well.

**Comment by adolfintel** [comment]
Yes, that works quite well. Thank you
