### ISSUE TITLE
About bus mouse

### ISSUE THREAD

**Issue by greatpsycho** [OBattler/86Box#145]
I know bus mouse uses IRQ2. However, 86box set to IRQ5 default. It seems to be the reason why the DOS mouse drivers does not recognize the bus mouse.

**Comment by OBattler** [comment]
IRQ 2 would be on PC/XT only. I suppose on AT and compatibles it should use IRQ 9 (which every BIOS maps to the IRQ 2 INT vector). I need to talk to waltje about this.

**Comment by OBattler** [comment]
I talked to Waltje, and he says IRQ 5 is correct.

**Comment by waltje** [comment]
As said, original boards were set to 5.  Later boards had jumpers or a dip switch to set it.  However, many (especially older) drivers will assume 5...

It can be fixed with a config option, defaulting to 5.
__
Sent from my Samsung Note4 LTE smartphone


-------- Original message --------
