### ISSUE TITLE
The sound is silent

### ISSUE THREAD

**Issue by ThingUroboros** [OBattler/86Box#146]
The sound is silent could it amplify it or the possibility of manual increase?

Thank you for answer

**Comment by dhrdlicka** [comment]
Config?

**Comment by ThingUroboros** [comment]
Hi i change this

i added four line:
 	alSourcef (source[0], AL_PITCH,    1.0f     );
        alSourcef (source[0], AL_GAIN,  1.0f);
        alSourcef (source[1], AL_PITCH,    1.0f     );
        alSourcef (source[1], AL_GAIN,  1.0f);

This is final in in soundopenal.c
108. alSource3f(source[0], AL_POSITION,        0.0, 0.0, 0.0);
        alSource3f(source[0], AL_VELOCITY,        0.0, 0.0, 0.0);
 	alSource3f(source[0], AL_DIRECTION,       0.0, 0.0, 0.0);
 	alSourcef (source[0], AL_PITCH,    1.0f     );
        alSourcef (source[0], AL_GAIN,  1.0f);
        alSourcef (source[0], AL_ROLLOFF_FACTOR,  0.0          );
        alSourcei (source[0], AL_SOURCE_RELATIVE, AL_TRUE      );
        check();
        alSource3f(source[1], AL_POSITION,        0.0, 0.0, 0.0);
        alSourcef (source[1], AL_PITCH,    1.0f     );
        alSourcef (source[1], AL_GAIN,  1.0f);
        alSource3f(source[1], AL_VELOCITY,        0.0, 0.0, 0.0);
        alSource3f(source[1], AL_DIRECTION,       0.0, 0.0, 0.0);
        alSourcef (source[1], AL_ROLLOFF_FACTOR,  0.0          );
122. alSourcei (source[1], AL_SOURCE_RELATIVE, AL_TRUE      );

I think the sound is better to hear.

Configuration here:
gameblaster = 0
gus = 0
ssi2001 = 0
voodoo = 0
model = 430vx
cpu_manufacturer = 0
cpu = 12
cpu_use_dynarec = 1
cpu_waitstates = 0
gfxcard = virge375
video_speed = 5
sndcard = sbawe32
cpu_speed = 14
has_fpu = 1
disc_a = 
disc_b = 
hdd_controller = none
mem_size = 32768
cdrom_drive = 68
cdrom_enabled = 1
cdrom_channel = 2
cdrom_path = 
hdc_sectors = 63
hdc_heads = 16
hdc_cylinders = 4048
hdc_fn = C:\emulatory\DISKY\MSDOS+CDROM.img
hdd_sectors = 0
hdd_heads = 0
hdd_cylinders = 0
hdd_fn = 
hde_sectors = 0
hde_heads = 0
hde_cylinders = 0
hde_fn = 
hdf_sectors = 0
hdf_heads = 0
hdf_cylinders = 0
hdf_fn = 
drive_a_type = 5
drive_b_type = 5
bpb_disable = 0
joystick_type = 0
mouse_type = 0
enable_sync = 1

[Joysticks]
joystick_0_nr = 0
joystick_1_nr = 0

[3DFX Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 1
render_threads = 2
recompiler = 1

**Comment by ThingUroboros** [comment]
But Windows Sound System is very silent in game Earth 2140

**Comment by OBattler** [comment]
The sound on the emulated WSS and SB16 is indeed very silent. I'm still looking into how to properly make it louder.

**Comment by OBattler** [comment]
Try the latest 86Box, it does seem to me like JosepMa's Sound Blaster mixer and DSP rewrites have improved on this.

**Comment by OBattler** [comment]
The sound gain control has now been implemented and should solve this problem.
