### ISSUE TITLE
Suddenly can't find any of my ROMs.

### ISSUE THREAD

**Issue by Insidious611** [OBattler/86Box#149]
Just replaced a build from early June which was working fine and seeing all my roms with #891 from CI and it is claiming that it can't find any roms.

**Comment by rwilming** [comment]
http://tinyurl.com/roms2017 the link with the romset from that is on the discord is outdated and it doesn't work with the newest 86box su use this romset

**Comment by dhrdlicka** [comment]
As said above. The ROMs directory has been reorganized. You might want to visit IRC instead of DIscord, it's more active.

**Comment by valnar1** [comment]
The link on the Wiki for dev builds doesn't work anymore.  Has it been replaced with a new one?

**Comment by dhrdlicka** [comment]
Yes, the Jenkins has been moved to http://ci.86box.net/. Would you mind telling us what wiki links to the old Jenkins page?

**Comment by valnar1** [comment]
I thought there were two (neither are official), but this is the one that comes up easily in Google.
https://emulation.miraheze.org/wiki/86Box
