### ISSUE TITLE
Can't load the Apple Rhapsody Developer Release isos

### ISSUE THREAD

**Issue by Ninetales420** [OBattler/86Box#153]
In the last couple of builds I wasn't able to load the Rhapsody Developer Release isos to it it would just show that There'S nothing in the emulated cd drive

**Comment by dhrdlicka** [comment]
Config?

**Comment by Ninetales420** [comment]
[86Box config.zip](https://github.com/OBattler/86Box/files/1166744/86Box.config.zip)

**Comment by OBattler** [comment]
Yeah, there's something in the current ISO loading code that doesn't like these ISO's. I'm going to look at this later today and see if I can find out why.

**Comment by OBattler** [comment]
Try now. It turns out the Rhapsody ISO's don't have a valid PVD, so the DOSBox-based ISO loading code was rejecting them, I now made the code default to Mode 1/2048 bytes per sector if it is unable to detect a PVD.
