### ISSUE TITLE
Carmageddon (1997) freezes a few seconds after race starts

### ISSUE THREAD

**Issue by Msteel1** [OBattler/86Box#154]
I'm using skylake optimized version of 86box, latest dev build (6cab132). Attached is my config file

- Host CPU i7-6700k
- Tested running game on Windows 98 and MS dos 6.22
- both 3dfx and software rendered versions.

[86box.zip](https://github.com/OBattler/86Box/files/1163992/86box.zip)

**Comment by MoochMcGee** [comment]
Try using the unoptimized build.

**Comment by Msteel1** [comment]
Thanks Mooch,
I tried the unoptimized build and the game played slightly longer, but still froze after about 30 seconds. If i ALT+TAB i can minimize the Dos game and get back to windows 98 desktop, so the issues seems to be limited to the game code crashing and not 86box.

**Comment by OBattler** [comment]
Try the game on the latest mainline PCem (you'll have to compile it from the latest source code in the repository) and see if you can reproduce the problem there. If yes, you'll have to report it on the PCem forum.

**Comment by Msteel1** [comment]
Mainline PCem has the same issue also, i have opened a topic on the PCem forum. 

Thanks!
