### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Breiztiger** [OBattler/86Box#159]
hi

when i try to compile 86box i get that error

cdrom_image.cc: In function 'int image_open(uint8_t, wchar_t*)':
cdrom_image.cc:988:31: error: 'wcstombs' was not declared in this scope
  wcstombs(afn, fn, sizeof(afn));
                               ^
Makefile.mingw:274: recipe for target 'cdrom_image.o' failed

i have try with gcc 6.3 and 7.1 (that gcc compiled good mame or other project)

thanks in advance for you help

**Comment by OBattler** [comment]
Use this development environment: http://tinyurl.com/pcemude .
