### ISSUE TITLE
86box doesn't recognize some ROMs

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#166]
Recent builds of 86box doesn't see ROMs for Cirrus Logic and nVidia cards (build from March 2017 doesn't have that problem).

**Comment by OBattler** [comment]
You need to compile 86Box manually, with the DEV_BRANCH=y parameter to make.

**Comment by ArtiomWin** [comment]
I have compiled recent build with Fluidsynth turned off (that's another story), but only ROMs for Riva 128 and TNT are recognized (no TNT2 or Cirrus Logic).

**Comment by BoisterousSleet75** [comment]
I think Cirrus Logic emulation is broken and unfinished. and I don't know why TNT2 aren't recognized.
