### ISSUE TITLE
Fluidsynth issue

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#168]
MinGW stops compilation with:
sound/midi_fluidsynth.c:8:10: fatal error: fluidsynth.h: No such file or directory
 #include <fluidsynth.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile.mingw:292: midi_fluidsynth.o] Error 1

**Comment by nerd73** [comment]
Delete the source and download/copy it again, extract it, and then edit line 59 in makefile.mingw of your 86box src to say:
FLUIDSYNTH = n
rather than:
FLUIDSYNTH = y

Then compile again.
Deleting the source and copying it again is required because otherwise it'll fail later on.

**Comment by OBattler** [comment]
New development environment with FluidSynth dependencies and GCC 7.1: http://tinyurl.com/de86box .

**Comment by ArtiomWin** [comment]
I've tried new enviroment with success, so readme.md can now be updated. Thank you.
