### ISSUE TITLE
86Box brokens network settings since revision #987

### ISSUE THREAD

**Issue by BoisterousSleet75** [OBattler/86Box#170]
Hi,

I have my compiled 86Box using the latest build (#991), When I select Network adapter, then I click "Yes", It crashes, and it says:

“86Box - an emulator for X86-based systems has stopped working"

![qq 20170822124849](https://user-images.githubusercontent.com/29619428/29549047-4393756a-8738-11e7-90e2-753a5961a2ff.png)

I also tried 86Box #987, Still same issue.

Is this bug or something else?

Thanks

**Comment by BoisterousSleet75** [comment]
My config:

```
[Machine]
model = 430vx
mem_size = 262144
nvr_path = D:\86Box\nvr\
cpu_use_dynarec = 1
cpu = 11
cpu_enable_fpu = 1

[Video]
gfxcard = px_trio64
video_speed = 5
voodoo = 1

[Input devices]
mouse_type = ps2

[Removable devices]
fdd_01_check_bpb = 0
fdd_02_check_bpb = 0
fdd_03_check_bpb = 0
fdd_04_check_bpb = 0
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 0, atapi_pio_and_dma
cdrom_01_ide_channel = 1:0

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 0
render_threads = 2
sli = 1
recompiler = 1

[Phoenix S3 Trio64]
memory = 4

[Sound]
sndcard = sbawe32
midi_device = system_midi

[Hard disks]
hdd_01_parameters = 63, 16, 16383, 0, ide_pio_and_dma
hdd_01_fn = D:\86Box\hd.img
hdd_01_ide_channel = 0:0
```

**Comment by BoisterousSleet75** [comment]
Here is the example of 86Box crash while NE2000 or RTL8029as selected: [https://streamable.com/mo0rz](url)

**Comment by BoisterousSleet75** [comment]
I decide to close the issues until OBattler fix the bug.

**Comment by OBattler** [comment]
It's fixed now.

**Comment by BoisterousSleet75** [comment]
Thanks for fixes selecting PCap bug. I'm closing the issues for now.
![qq 20170823072420](https://user-images.githubusercontent.com/29619428/29591992-483e7b7c-87d4-11e7-8aaa-995675a4adb2.png)
