### ISSUE TITLE
BeOS issue

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#172]
BeOS installation CDs for earlier versions don't see hard disk, for example, BeOS 4.5 gives: "Boot failure: The boot loader was unable to find a BeOS volume to boot from. If you are trying to boot from the CD-ROM and find that you are unable to do so, press space during the boot sequence to enter the boot menu and select "Boot from CD-ROM" as the boot volume.".

**Comment by claunia** [comment]
@ArtiomWin are you using a .BIN/.CUE that correctly describe the 3 tracks present in the CD or the host drive?

What channel is the emulated CD-ROM connected to?

What motherboard are you using?

BeOS gives that error in a lot of real motherboards because of problems with the IDE controller and/or channel.

**Comment by ArtiomWin** [comment]
Tested motherboard - ASUS P/I-P55T2P4
CD-ROM - ATAPI (PIO and DMA) - channel 0:1
Most of BeOS install images are in .mdf/.mds (I've downloaded the from BetaArchive) (BeOS 3.1 is .bin/.cue, BeOS 4.5 is .iso)

**Comment by OBattler** [comment]
Try the latest 86Box. Back in August, the PIIX IDE bus master for DMA was not working right (if at all) and there were other IDE bugs as well since fixed, and I suspect that might have been causing the problem.

**Comment by ArtiomWin** [comment]
I've tried revision 1378. Still the same thing.
![20180120_184036](https://user-images.githubusercontent.com/31134876/35185234-eaed49c6-fe11-11e7-9d2c-83bd2956ac50.png)
![20180120_184233](https://user-images.githubusercontent.com/31134876/35185235-eb2047d6-fe11-11e7-9dc1-bc398fde28b0.png)
![20180120_183315](https://user-images.githubusercontent.com/31134876/35185236-eb524a4c-fe11-11e7-821b-b64e3287ef4d.png)

**Comment by ArtiomWin** [comment]
Here's link to archive with config and disk images: https://mega.nz/#!FIsEzTTK!9inXte_Fg-Bm3Ma2_5dscHKirMWtiF8J9PGeiaJvYAs

**Comment by OBattler** [comment]
OK, I'm downloading this. Hopefully I can get this done today.

**Comment by OBattler** [comment]
I just look at this, and I can't see anything wrong on the emulator's side. I also heard that this issue tends to happen a lot on real hardware as well, so unfortunately, I have to close this with "can't fix".

**Comment by mietek** [comment]
I was able to get past the same issue with BeOS 5 and VMware Fusion by splitting the original multi-track installation CD image into [three individual tracks](https://www.dropbox.com/s/lqnpgcbdwwin0ch/BeOS_5_Individual_Tracks.zip), and mounting them in three separate virtual CD drives.
