### ISSUE TITLE
Cirrus for dev branch testing

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#177]
For those who are interested in dev branch, even if you select cirrus at compile, there's no device.
I think you should add these lines in video.c
#ifdef DEV_BRANCH
#ifdef USE_CIRRUS
        {"Cirrus Logic CL-GD5429",                 "cl_gd5429",		&gd5429_device,              GFX_CL_GD5429},
		{"Cirrus Logic CL-GD5446",	 	           "cl_gd5446",		&gd5446_device,              GFX_CL_GD5446},
#endif
#endif

Regards.

**Comment by ArtiomWin** [comment]
Thanks, but can you do it for other Cirrus cards. Then I tried to add other cards manually, I'd got problems during compilation:
video/video.c:88:62: error: 'GFX_CL_GD5422' undeclared here (not in a function); did you mean 'GFX_CL_GD5429'?
  {"Cirrus Logic CL-GD5422",   "cl_gd5422",  &gd5422_device,  GFX_CL_GD5422},
                                                              ^~~~~~~~~~~~~
                                                              GFX_CL_GD5429
video/video.c:90:62: error: 'GFX_CL_GD5430' undeclared here (not in a function); did you mean 'GFX_CL_GD5422'?
  {"Cirrus Logic CL-GD5430",   "cl_gd5430",  &gd5430_device,  GFX_CL_GD5430},
                                                              ^~~~~~~~~~~~~
                                                              GFX_CL_GD5422
video/video.c:91:62: error: 'GFX_CL_GD5434' undeclared here (not in a function); did you mean 'GFX_CL_GD5430'?
  {"Cirrus Logic CL-GD5434",   "cl_gd5434",  &gd5434_device,  GFX_CL_GD5434},
                                                              ^~~~~~~~~~~~~
                                                              GFX_CL_GD5430
video/video.c:92:62: error: 'GFX_CL_GD5436' undeclared here (not in a function); did you mean 'GFX_CL_GD5434'?
  {"Cirrus Logic CL-GD5436",   "cl_gd5436",  &gd5436_device,  GFX_CL_GD5436},
                                                              ^~~~~~~~~~~~~
                                                              GFX_CL_GD5434
video/video.c:93:62: error: 'GFX_CL_GD5440' undeclared here (not in a function); did you mean 'GFX_CL_GD5430'?
  {"Cirrus Logic CL-GD5440",   "cl_gd5440",  &gd5440_device,  GFX_CL_GD5440},
                                                              ^~~~~~~~~~~~~
                                                              GFX_CL_GD5430

**Comment by Altheos** [comment]
Just add theses lines in ibm.h for other CL-GD
	        GFX_CL_GD5422,  /*Cirrus Logic CL-GD5422*/
		GFX_CL_GD5430,  /*Cirrus Logic CL-GD5430*/
		GFX_CL_GD5434,  /*Cirrus Logic CL-GD5434*/
		GFX_CL_GD5436,  /*Cirrus Logic CL-GD5436*/
		GFX_CL_GD5440,  /*Cirrus Logic CL-GD5440*/

**Comment by basic2004** [comment]
I use this patch for testing.
I don't have 6235 rom, but this will working when this detecting this romfile.
```
diff -urN master/src/ibm.h dev/src/ibm.h
--- master/src/ibm.h	2017-09-02 14:39:26 +0900
+++ dev/src/ibm.h	2017-09-03 16:19:53 +0900
@@ -536,7 +536,13 @@
         GFX_RIVA128,
         GFX_HERCULESPLUS,
         GFX_RIVATNT2,
-
+        GFX_CL_GD5422, /*Cirrus Logic CL-GD5422*/
+        GFX_CL_GD5430, /*Cirrus Logic CL-GD5430*/
+        GFX_CL_GD5434, /*Cirrus Logic CL-GD5434*/
+        GFX_CL_GD5436, /*Cirrus Logic CL-GD5436*/
+        GFX_CL_GD5440, /*Cirrus Logic CL-GD5440*/
+        GFX_CL_GD6235, /*Cirrus Logic CL-GD6235*/
+        GFX_DIA5430, /*Diamond CL-GD5430*/
 	GFX_TRIGEM_UNK,
         GFX_OTI037,	/*Oak OTI-037*/
 
diff -urN master/src/video/video.c dev/src/video/video.c
--- master/src/video/video.c	2017-09-02 14:39:26 +0900
+++ dev/src/video/video.c	2017-09-03 16:39:38 +0900
@@ -83,6 +83,19 @@
         {"ATI VGA Wonder XL24 (ATI-28800-6)",      "ati28800w",		&ati28800_wonderxl24_device, GFX_VGAWONDERXL24},
         {"ATI VGA Edge-16 (ATI-18800)",            "ati18800",		&ati18800_device,            GFX_VGAEDGE16},
         {"CGA",                                    "cga",		&cga_device,                 GFX_CGA},
+#ifdef DEV_BRANCH
+#ifdef USE_CIRRUS
+        {"Cirrus Logic GD5422",                    "cl_gd5422",     &gd5422_device,              GFX_CL_GD5422},
+        {"Cirrus Logic GD5429",                    "cl_gd5429",     &gd5429_device,              GFX_CL_GD5429},
+        {"Cirrus Logic GD5430",                    "cl_gd5430",     &gd5430_device,              GFX_CL_GD5430},
+        {"Cirrus Logic GD5434",                    "cl_gd5434",     &gd5434_device,              GFX_CL_GD5434},
+        {"Cirrus Logic GD5436",                    "cl_gd5436",     &gd5436_device,              GFX_CL_GD5436},
+        {"Cirrus Logic GD5440",                    "cl_gd5440",     &gd5440_device,              GFX_CL_GD5440},
+        {"Cirrus Logic GD5446",                    "cl_gd5446",     &gd5446_device,              GFX_CL_GD5446},
+        {"Cirrus Logic GD6235",                    "cl_gd6235",     &gd6235_device,              GFX_CL_GD6235},
+        {"Diamond CL-GD5430",                      "dia5430",       &dia5430_device,             GFX_DIA5430},
+#endif
+#endif
         {"Diamond Stealth 32 (Tseng ET4000/w32p)", "stealth32",		&et4000w32p_device,          GFX_ET4000W32},
         {"Diamond Stealth 64 DRAM (S3 Trio64)",    "stealth64d",	&s3_diamond_stealth64_device,GFX_STEALTH64},
         {"Diamond Stealth 3D 2000 (S3 ViRGE)",     "stealth3d_2000",	&s3_virge_device,            GFX_VIRGE},
```

**Comment by waltje** [comment]
Done, sorry for the delay in doing this!
