### ISSUE TITLE
Nasty-sounding sound bug with AWE32 emulation under Win98.

### ISSUE THREAD

**Issue by johnsirett** [OBattler/86Box#178]
The problem is a loud, harsh-sounding noise occurring periodically and for around 3 seconds each time. Noise begins after Win98 guest successfully boots, but can continue after system soft-reboots. Other normal sound is also heard under this harsh noise. Haven't extensively tested this, but I believe the issue only occurs with the AWE32 card.

Host System:
```
Windows 10 Pro
AMD Ryzen 7 1800X
16 GB RAM
```

Emulated System:
```
ASUS Socket 7 VX board
Pentium MMX 166
64 MB RAM
Pheonix S3 Trio64 + Voodoo 2
PS/2 Mouse, no ports enabled
SB AWE32 (MPU-401 attached to System MIDI) + Seperate GUS
No network
```

Regression testing by myself suggests bug was introduced with this commit:
https://github.com/OBattler/86Box/commit/ac0cb476f9baf4e9c1a49f7157ab4baac4a13383

**Comment by OBattler** [comment]
Try the latest build, it should fix the issue.

**Comment by johnsirett** [comment]
Bug fixed, thank you.
