### ISSUE TITLE
General protection fault

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#179]
I have issues with launching Windows 3.1 (Compaq OEM).
1. When Windows is going to launch Program Manager, it gives: "Application error: PROGMAN caused a General Protection Fault in module <unknown>14EF:11D4 |PROGMAN will close."
2. Then EMM386 says: "EMM386 has detected error #06 in an application at memory address 00B8:0BCF. To minimize the chance of data loss, EMM386 has halted your computer. For more information, see the README.TXT file."

**Comment by OBattler** [comment]
Post your 86box.cfg please.

**Comment by ArtiomWin** [comment]
[86box.zip](https://github.com/OBattler/86Box/files/1269232/86box.zip)
Here you are. I've tried on some other configurations. It works on 486, but fails to start on Pentium boards.
After first configuration on AMI WinBIOS 486, I've tried to launch in Premiere/PCI II again, then in Advanced/ZP. Now it gives: "Application error: TABWORKS caused a General Protection Fault in module <unknown>14F7:A26Eà|TABWORKS will close."

**Comment by OBattler** [comment]
I just installed Windows 3.1 onto the Premiere/PCI II and it works fine. Could you please upload your hard disk image somewhere so I can test your specific copy of Windows 3.1?

**Comment by ArtiomWin** [comment]
Well, here is disk image (please rename file extension from .0xx.zip to .zip.0xx before extending). 
[Compaq Presario 978CDTV.006.zip](https://github.com/OBattler/86Box/files/1273133/Compaq.Presario.978CDTV.006.zip)
[Compaq Presario 978CDTV.007.zip](https://github.com/OBattler/86Box/files/1273134/Compaq.Presario.978CDTV.007.zip)
[Compaq Presario 978CDTV.008.zip](https://github.com/OBattler/86Box/files/1273138/Compaq.Presario.978CDTV.008.zip)
[Compaq Presario 978CDTV.009.zip](https://github.com/OBattler/86Box/files/1273136/Compaq.Presario.978CDTV.009.zip)
[Compaq Presario 978CDTV.010.zip](https://github.com/OBattler/86Box/files/1273137/Compaq.Presario.978CDTV.010.zip)
[Compaq Presario 978CDTV.001.zip](https://github.com/OBattler/86Box/files/1273135/Compaq.Presario.978CDTV.001.zip)
[Compaq Presario 978CDTV.002.zip](https://github.com/OBattler/86Box/files/1273139/Compaq.Presario.978CDTV.002.zip)
[Compaq Presario 978CDTV.003.zip](https://github.com/OBattler/86Box/files/1273140/Compaq.Presario.978CDTV.003.zip)
[Compaq Presario 978CDTV.004.zip](https://github.com/OBattler/86Box/files/1273141/Compaq.Presario.978CDTV.004.zip)
[Compaq Presario 978CDTV.005.zip](https://github.com/OBattler/86Box/files/1273142/Compaq.Presario.978CDTV.005.zip)

**Comment by OBattler** [comment]
I just tested your hard disk and it seems the Compaq-specific drivers mess with it - if I restore Windows to the default drivers, it works.

**Comment by ArtiomWin** [comment]
Error shows up after I've set display driver to VGA and mouse to serial or PS/2 depending on emulated machine.

**Comment by ArtiomWin** [comment]
It works on i430hx and i430vx chipset. So, system may simply conflict with chipset.
