### ISSUE TITLE
Feature Suggestion: Turbo button emulation option

### ISSUE THREAD

**Issue by johnsirett** [OBattler/86Box#180]
Many PCs of the late 80s / early 90s came with a little case button marked 'Turbo'. Contrary to the name, the purpose of this button was to slow the machine down from speedy modern CPU speeds down to the snails pace of the 4.77Mhz 8088 to provide compatibility for badly-coded timing loops in old PC 5150 software/games.

Given 86box emulates many MUCH faster systems than 8088, should 86box add a GUI option to use 'turbo/slow' modes?

**Comment by waltje** [comment]
I like this.  I was considering suggesting some kind of 'Toolbar' in the UI, we could have this there.  My old PCs both had this in the keyboard, too... ctrl-alt-pgup and -pgdn.

Will forward this to the project manager, who will decide on if/when :)
