### ISSUE TITLE
>1050 issues

### ISSUE THREAD

**Issue by valnar1** [OBattler/86Box#183]
On any version greater than #1050, I have issues with my Win98 installation on the ASUS P/I-P55T2P4.  The BIOS takes forever to find or pass by unneeded IDE ports and when it boots, the mouse or keyboard does not work.  I need to close the emulator.  Back to #1050 and all is well.  Sanitized config attached.

[86box-cfg.zip](https://github.com/OBattler/86Box/files/1275109/86box-cfg.zip)

**Comment by OBattler** [comment]
This was fixed quite some time ago now.
