### ISSUE TITLE
Mouse/keyboard hang since build 1051

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#185]
Config used => Asus P54TP4XE (PCI), PS2 2 Button-Mouse, PC-DOS 7, MS Mouse 8.20, Windows 3.1
Mouse always hangs on windows start and sometimes keyboard hangs too.

Problems seems to be here  `if ((keyboard_at.mem[0] & 0x02) && mouse_enabled)`

**Comment by OBattler** [comment]
The question is, why does the BIOS keep PS/2 mouse disabled even when it's attached? I need to look into that.

**Comment by OBattler** [comment]
Go to CMOS Setup, and there go to BIOS features setup, and see what PS/2 Mouse Function Control is set to there.

**Comment by ArtiomWin** [comment]
Actually most of Socket 4, 5 and 7 chipsets have this problems: some chipsets have broken keyboard only while some ones have broke both mouse and keyboard. The exception (or one of them) is ASUS P/I-P55T2P4.

**Comment by OBattler** [comment]
I fixed it last night.

**Comment by Altheos** [comment]
Fixe with build 1057 (tried with PS2 mouse on PS/1 computer).
Thanks
