### ISSUE TITLE
Dynamic compiler and UNIX

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#186]
86box refused to run installation programs of UNIX-based systems incl. SCO UNIX with dynamic recompiler turned on - it (binary) gives error "Deleting deleted block" and closes down.

**Comment by MoochMcGee** [comment]
Check to see if this happens on the latest mainline PCem. If it does,
report it on the PCem forums.

**Comment by ArtiomWin** [comment]
Well, I'll try write here (I've registered but not activated yet).
P.S. I've tried Riva and Cirrus Logic cards:
Cirrus Logic - all cards give black screen so Windows (3.1/95) doesn't work with them
Riva 128/TNT - Windows even with installed drivers refuses to set up anything higher than VGA (640x480/16 colors).

**Comment by MoochMcGee** [comment]
We already know. Riva 128 and Riva TNT emulation is mine, and it's nowhere near done. It works well enough for DOS and Linux in VESA mode tho.

**Comment by OBattler** [comment]
The Cirrus is mine (I replaced Sarah's very incomplete emulation with code ported from QEMU) but it's still unfinished.

**Comment by OBattler** [comment]
This has been fixed about a month ago.
