### ISSUE TITLE
IBM PS/1 2133 won't boot with dynarec

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#188]
Hello,

in order to boot IBM PS/1 2133, I had to uncheck "Dynamic Recompiler".
Boot in dynarec gives 102 error = 102   System Board Error; Timer failure on PS/2 bios.

**Comment by nerd73** [comment]
Same problem on the m80-486.

**Comment by Altheos** [comment]
Seems to be solved with latest build.
Though, 2133 POST still output 221 error (ROM to RAM copy failed) and 129 (cache failed).
