### ISSUE TITLE
XT's doesn't loading from diskette image.

### ISSUE THREAD

**Issue by dimasik79** [OBattler/86Box#192]
I  insert an image, but XT machine(every) doesn't want to load from image . This image is MS-DOS 5.0 diskette. 
Maybe I doing something wrong? Or it need to be configurated? 
And how to configurate bios in XT in this emulator?

**Comment by dhrdlicka** [comment]
There are many kinds of MS-DOS 5.0 diskettes and many kinds of floppy drives emulated by 86Box. Some of them don't work with the XT. Make sure your floppy drives *and* images are 5.25" 720k or smaller.
