### ISSUE TITLE
Samsung SPC-4200 must not remap top 384K memory statically.

### ISSUE THREAD

**Issue by greatpsycho** [OBattler/86Box#193]
Samsung SPC-4200P machine remaps top 384K memory  via chipset configuration register when 1MB memory installed enviroment and it it already implemented in SCAT chipset emulation.

So machine_at_scat_remap_init function is an unnecessary function and it must cause problems in an environment with 1MB of memory.

**Comment by waltje** [comment]
greatpsycho, please contact me on the irc channel, I have a SCAT datasheet for you.
