### ISSUE TITLE
IBM PS/1 (2011/2121/2133) broken since build #1125

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#203]
Since build 1125, no matter config i use, screen goes black with PS/1 model 2011, 2121 and 2133.
Tested OK with 1124 as these models boot fine.

**Comment by TC1995** [comment]
I think it's because the "if (AT)" statement doesn't get triggered on mem_add_bios(), waltje is working on this.

**Comment by Altheos** [comment]
Fixed in build #1140. Thanks waltje.
