### ISSUE TITLE
Web browsing sites with https issue

### ISSUE THREAD

**Issue by jznomoney** [OBattler/86Box#207]
I don't know it's the latest Windows 10 v. 1709 but sites that use https protocol do not work in any web browser.  I tried many different operating systems and both pcap or slirp.  I tried it on another pc I have but it also is running 10 v 1709.  Regular http sites work.  Anyone have an idea?

**Comment by OBattler** [comment]
Older browsers don't support the modern versions of SSL or TLS needed by modern https sites.

**Comment by waltje** [comment]
Hi... it does not matter which operating system you use to run 86Box on; if you use a browser inside it, it depends on that browser's version and age, as well as on the operating you are using it with.  All this happens INSIDE the emulator.  Older software usually does not 'keep up' with technology, and, so, some websites will not, or barely, work with those older browsers.

Nothing can be done about that, sorry..
