### ISSUE TITLE
System won't boot beyond BIOS HDD detection phase.

### ISSUE THREAD

**Issue by johnsirett** [OBattler/86Box#209]
As the title says. System basically hangs after finding the CD drive, before activating the boot. System also hangs in the "IDE HDD AUTO DETECTION" part of the BIOS.

Config attached.
Regression was introduced in commit 2f2785c.

**Comment by johnsirett** [comment]
[86box.cfg.txt](https://github.com/OBattler/86Box/files/1415769/86box.cfg.txt)

**Comment by OBattler** [comment]
Build 1208 fixes this.
