### ISSUE TITLE
Mouse inversion issue..

### ISSUE THREAD

**Issue by johnsirett** [OBattler/86Box#211]
Mouse is inverted for Y-axis motion: up = down and vice versa. Haven't searched for the regression, but know it was introduced somewhere between commit 2f2785c and the build that fixed issue #209, or perhaps a few builds after.

[86box.cfg.txt](https://github.com/OBattler/86Box/files/1424947/86box.cfg.txt)

**Comment by waltje** [comment]
Fixed as of #1231.
