### ISSUE TITLE
SB AWE 32 Aweutil.exe initialization failes since build #1145

### ISSUE THREAD

**Issue by MartinVlaswinkel** [OBattler/86Box#212]
Aweutil doesn't initialize anymore and thus not all software / games recognizes the Wavetable part of the soundcard anymore, not even Diagnose.exe, only FM synthesis.

The thing that I found has changed in the configuration of the AWE32 within the 86Box settings itself is the addition of EMU8000 Address option in de device configuration.

Might have something to do with the PCem commit that has been applied since #1145?
#1144 still works satisfactory and no issues there.

All this in a simple 486 config DOS 6.22 environment without complicated settings like SCSI or even Network, config included in this post

[86box_cfg.zip](https://github.com/OBattler/86Box/files/1438002/86box_cfg.zip)

**Comment by MartinVlaswinkel** [comment]
btw, even with 'emu_addr = 0620' added no avail, just found out that line was missing in my cfg

**Comment by OBattler** [comment]
The latest commit fixes the issue, just change that emu_addr to emu_base in your configuration file.
