### ISSUE TITLE
Amstrad PC1640 - EGA not working with GEM

### ISSUE THREAD

**Issue by waltje** [OBattler/86Box#213]
GEM does not seem to be happy with the ECD350 (EGA) mode of the 1640's video controller, it displays junk.  Most likely videoram issue.

It does work if you force the display to Mono mode.

**Comment by OBattler** [comment]
Are you sure it would work on the real Amstrad PC1640 in EGA mode? And does it work with an actual emulated EGA card?

**Comment by OBattler** [comment]
The EGA fixes I did recently, might fix this.

**Comment by OBattler** [comment]
It turns out there might have been no bug to begin with - the BIOS by default configures itself into CGA mode (which is default) until it is told to boot in EGA mode. So either use the NVR from the repository of use whatever is needed to reconfigure the BIOS.
