### ISSUE TITLE
Texture missing in a dos game only in 86box (shows correctly in pcem)

### ISSUE THREAD

**Issue by Solstar** [OBattler/86Box#214]
using win 98 and booting up the game "Eradicator" (1996-ish), using latest version of 86box, all the texture are missing, showing all flat polygons

https://i.imgur.com/qgVVoGd.png

using the exact same 86box config with pcem12,with the exepction of using a p133 instead of a p150, (using even the same exact hard disk image), game shows and run correctly

https://i.imgur.com/VDX3lxo.png

**Comment by TC1995** [comment]
Well, we are still some voodoo commits behind, but we'll get there.

**Comment by OBattler** [comment]
Try the latest build of 86Box and see if it still happens.

**Comment by Solstar** [comment]
Just tried the latest optimized exe and still same issue. I'll try with the non-optimized one

**Comment by waltje** [comment]
Solstar, could you please come to the IRC channel and talk to me?  I would like you to test something for me regarding this bug...  thanks!

**Comment by Solstar** [comment]
@waltje Sorry but when you wrote me that it was past bedtime for me already..I can do that today of course

**Comment by OBattler** [comment]
This has been fixed by now, so I'm closing this.
