### ISSUE TITLE
ATI mach64GX BIOS Dissonance

### ISSUE THREAD

**Issue by PeladoFeo** [OBattler/86Box#215]
86Box always uses the ATI mach64GX PCI BIOS,
even if I choose to emulate its VLB counterpart.

**Comment by TC1995** [comment]
because I think the code of the mach64gx bios contains support for both VLB and PCI variants as well.

**Comment by PeladoFeo** [comment]
I mean, 86Box should use the ATI mach64GX VLB BIOS when applicable.

**Comment by OBattler** [comment]
Do you have any link to the Mach64GX VLB BIOS?

**Comment by PeladoFeo** [comment]
Yes, [here](http://www.planetemu.net/rom/mame-roms/mach64isa-1).

**Comment by TC1995** [comment]
Well, is there, by any chance, a trio64 vlb bios?

**Comment by PeladoFeo** [comment]
It can be good to add an ATI mach64GX ISA BIOS to 86Box, after all.

**Comment by ArtiomWin** [comment]
Well, here's my 2 cents: if we talk about variations of hardware for different buses, SoundBlaster 16 has versions both for ISA and PCI (PCI version is based on Ensoniq AudioPCI).

**Comment by OBattler** [comment]
No, the PCI Sound Blaster you're talking about is the Sound Blaster 128, which we do emulate (snd_audiopci.c).

**Comment by OBattler** [comment]
This is now done.
