### ISSUE TITLE
Ask implementation of 286/386 SX machines from Pcem

### ISSUE THREAD

**Issue by Fenix770** [OBattler/86Box#218]
Hello.

I want to ask if it's possible to add the newer machines from Pcem.
Greapsycho added GW-286CT GEAR,  Samsung SPC-4216P and KMX-C-02 (386SX)
The 286s have  82C835 and the KMX is a 386 SX. which has 82C836 chip all of them are SCAT/SCATsx chipset. 

Thanks in Advance!

**Comment by OBattler** [comment]
86Box v2.0 is on a feature freeze concerning new devices and machines, so I am going to look into this for 86Box v3.0.
