### ISSUE TITLE
MS Serial mouse segfaulting latest build

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#219]
Microsoft serial mouse is segfaulting latest build with : 
0x00583375 in sermouse_close at mouse_serial.c:200
200         dev->serial->rcr_callback = NULL;

Config : AMI WinBIOS 486, 4 Mo, Tseng ET4000, MS serial mouse.

You need to save config, close emulator, then restart and change config again to reproduce.

**Comment by waltje** [comment]
Fixed in #1302.
