### ISSUE TITLE
Compilation under Linux

### ISSUE THREAD

**Issue by mrnamwen** [OBattler/86Box#220]
First off, apologies if this has been addressed before but I can't seem to find any reliable information about this. From what I understand, 86Box should still be working under Linux as long as you compile it. However, it appears that the code is only designed to build under a MinGW environment.

What is the best way to compile under a Linux system, if any?

**Comment by claunia** [comment]
@mrnamwen cross-compilation is supported. It will not work in Linux until the wx interface is done (dunno current status, @waltje was working on it).

**Comment by waltje** [comment]
86Box currently is a Windows application.  It can be built using the MinGW aka MSYS2 development system, which, indeed, is based on GCC and friends.

To compile it under Linux, you will have to:

- get and install the MinGW (!) cross-compiling system so you can compile applications for
  Windows
- get and install the remaining libraries needed (only two I believe.)

This will allow you to build 86Box on Linux.  It will still be a Windows application, though.

If you wanted to build it as a Linux application, well, you will have to wait.  I have it, and it works, but it is not in a state where I want it 'out' yet. Most issues are with Wx stability, the actual "core code" works
just fine.

**Comment by mrnamwen** [comment]
I see, thanks anyways.

As for the graphical library, why not use something like Qt instead? The open source version is under the LGPL iirc and on top of that it works on practically every platform, pretty stable too.

Of course it's your choice if you want to opt for that.
