### ISSUE TITLE
Trident TVGA8900D only displays monochrome colors.

### ISSUE THREAD

**Issue by johnsirett** [OBattler/86Box#221]
Regression tested this to commit 55d2e3c. Suspect it has something to with the "svga->sense" variable. Setting that variable to 0x10 fixes the issue, but is probably endemic of some deeper problem that someone with experience with the SVGA code would be able to pinpoint.

Machine is an AMI WinBIOS 486. My config is [86box.cfg.txt](https://github.com/OBattler/86Box/files/1556750/86box.cfg.txt)

**Comment by johnsirett** [comment]
Whoops, don't know why I said it was commit af08e25 that introed the bug. It was 55d2e3c :P

**Comment by OBattler** [comment]
I'm going to look at this, probably going to use a workaround until someone finds the right way to do this.

**Comment by OBattler** [comment]
This is now fixed with a workaround, pending a proper fix.
