### ISSUE TITLE
(FEATURE REQUEST) Soyo 4SA2 Emulation

### ISSUE THREAD

**Issue by PeladoFeo** [OBattler/86Box#224]
In order to emulate the title motherboard in 86Box,
we need code for PC87332VLJ emulation.
[PC87332VLJ.pdf](https://github.com/OBattler/86Box/files/1564211/PC87332VLJ.pdf)

**Comment by OBattler** [comment]
86Box v2.0 is on a feature freeze regarding the addition of machines and devices right now, so this is slated for 86Box v3.0.
