### ISSUE TITLE
Mouse cursor doesn't release after fullscreen

### ISSUE THREAD

**Issue by TheMadLynx** [OBattler/86Box#225]
Switching to the fullscreen and back with Direct3D renderer selected prevents the proper cursor release. In fact you can capture and "release" the cursor, BUT released cursor movement will be locked in the upper left corner area size of which depends on 86Box window resolution.

![86box_cursor](https://user-images.githubusercontent.com/30351464/34324543-97f2963a-e887-11e7-8c10-014e8208e9ec.png)

**Comment by OBattler** [comment]
Check if this still affects the latest 86Box.

**Comment by TheMadLynx** [comment]
Checked the latest build and the issue is gone. Thank you!

**Comment by redphoenix2k** [comment]
the problem is back in the latest experimental builds

**Comment by redphoenix2k** [comment]
it remains stuck in inside the 86box windows on win10, u can move it inside but u cant make it leave 

u have to do ctrl+alt+delete to release it (and restart the virtual machine..)

**Comment by daviunic** [comment]
I can confirm this issue as well, on 86Box build 1830. The latest unofficial build has a different problem where mouse can leave 86Box window, but the renderer will hang soon after that, requiring you to terminate the 86Box process.
