### ISSUE TITLE
Extended Keys Don't Seem To Work

### ISSUE THREAD

**Issue by SeanRamey** [OBattler/86Box#226]
I'm writing a program that installs a custom Keyboard ISR to handle key inputs. I'm working on adding extended key functionality, but 86Box doesn't seem to register extended keys. I've found that the arrow keys are mapped to the keypad arrow keys, and the right alt is the same as the left alt. This is not correct unless 86Box is trying to emulate an 83 Key Model F keyboard, but this doesn't make sense for newer machines such as the [Socket 7 HX] Acer M3a. On that specific machine, you can't enter the BIOS setup because you can't press the Ctrl-Alt-Esc key combo that it asks for. EDIT: I've now noticed that there is a dedicated Ctrl-Alt-Esc button in the menu. Is this simply there to work around the keyboard not being fully emulated?
 
Also, I've tried my program under Dosbox and it works perfectly.

**Comment by OBattler** [comment]
This should be fixed now, it was a bug in the 8042 (AT and PS/2 keyboard controller) emulation, in addition to missing Acer-specific I/O ports 0xEA and 0xEB. Now this should work.

> I've found that the arrow keys are mapped to the keypad arrow keys, and the right alt is the same as the left alt.
For the earliest emulated machines (IBM PC, XT, and XT clones), 86Box indeed emulates the PC/XT keyboard controller and the PC/XT 83/84-key keyboard.
For the Acer, as I explained above, it is a completely unrelated bug.

In any case, try the latest 86Box and see if it works correctly now.

**Comment by OBattler** [comment]
This turned out to be a bug in your own program which you solved, so closing this.
