### ISSUE TITLE
No option for FPU on IBM PC and XT machines

### ISSUE THREAD

**Issue by SeanRamey** [OBattler/86Box#228]
The option checkbox to add an FPU to the IBM PC and IBM XT machines is greyed out for some reason.
![86box nofpu](https://user-images.githubusercontent.com/3057229/34769461-7fddf776-f5c3-11e7-9bfa-52e771068c12.png)

**Comment by OBattler** [comment]
This is not a bug, the 8087 is not emulated yet. 8087 emulation is slated for 86Box v3.0 right now.
