### ISSUE TITLE
AMI 386DX(/25) A:=1.2MB diskette=360K

### ISSUE THREAD

**Issue by waltje** [OBattler/86Box#229]
System will not boot from 360K diskette (DOS 3.31) unless both BIOS and 86Box types are set to 360K.

**Comment by OBattler** [comment]
Make sure the 1.2 MB drive is not dual-RPM - most BIOS'es don't support dual-RPM 1.2 MB drive, but only single-RPM ones (though there are exceptions). The AMI 386DX BIOS for example only supports 300 kbps (used for 2DD floppies at 360 RPM) and 500 kbps rates (used for 2HD floppies), and not the 250 kbps rate needed for 2DD floppies at 300 RPM.

**Comment by OBattler** [comment]
OK, confirmed. The AMI 386DX BIOS will not boot from a 360k diskette on a dual-RPM 1.2 MB drive, so use a single-RPM 1.2 MB drive.
