### ISSUE TITLE
IBM PS/2 50 memory expansion

### ISSUE THREAD

**Issue by Fenix770** [OBattler/86Box#232]
Hello.

I tested the last commit of today. I've been able to run the PS/2 50 with an 80 ESDI hard disk, and 4mb RAM. I copied all files containing "FCFF" to  reference floppy disk and it seemed to work. Once configured the mem command of PC-DOS 4.0 count the XMS correctly (3.5 MB). I also copied data from the update disk as menu advised.

The only problem is when I load XMA2EMS.SYS (to emulate EMS) in CONFIG.SYS file 
it says "cannot find the adapter". The other device driver XMAEM.SYS is for 80386 machines.
Do I need a hardware specific device driver loaded before XMA2EMS.SYS? 

Thanks in advance!

**Comment by OBattler** [comment]
This memory expansion card either has no EMS support or EMS support is not implemented (though the MCA reads and writes I logged seem not to indicate any EMS configuration).
For 86Box v3.0, I'm going to look at emulating the actual PS/2 model 50 memory expansion card (ID FEFE), which does have EMS support. That is, provided I can find any documentation of that card.

**Comment by OBattler** [comment]
Going to close this until v3.00 (or v2.10 before it) starts development.
