### ISSUE TITLE
New compile warning.

### ISSUE THREAD

**Issue by waltje** [OBattler/86Box#236]
mem.c: In function 'mem_readl_phys':
mem.c:271:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  return *(uint32_t *) temp;
  ^~~~~~
mem.c: In function 'mem_writel_phys':
mem.c:279:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  *(uint32_t *) temp = val;
  ^

**Comment by OBattler** [comment]
I fixed this now.
