### ISSUE TITLE
VGA rendering glitch on Commander Keen 4 and 5

### ISSUE THREAD

**Issue by kibmcz** [OBattler/86Box#244]
On builds newer than revision 9e487d9 I have noticed VGA render glitches in Commander Keen 4 and 5.
Have tried on latest developer build and behavior is still present.

Video showing the glich:
https://www.youtube.com/watch?v=9BxmpYTBDzA

Machine: [Socket 7 VX] Epox p55-VA
CPU Type: Intel
CPU: Pentium MMX 233
Memory 64MB
Video: [PCI] ATI Graphics Pro Turbo (Mach64 GX)

Issue happened on multiple configurations tested on VGA based adapters but doesn't happen on CGA (Tested using Commander Keen 4 CGA).

**Comment by OBattler** [comment]
Test this on PCem too and see if it also happens there. If yes, then it's either an incompatibility of the game with VGA, or a bug common to both emulators. If not, then it's a bug specific to 86Box.

**Comment by OBattler** [comment]
OK, then could you please upload the configuration file, the NVR folder, and the hard disk image somewhere so I can reproduce the bug and have a go at fixing it?

**Comment by kibmcz** [comment]
Here you go this should provide the needed files to help fix it.

https://mega.nz/#!0E0CQJ5Z!X4VIk757TTpopHq9CYQYHmRTdDO8fHwaNxLfoMDdG3o

**Comment by OBattler** [comment]
Thank you very much. The commit I made just now fixes this issue.
