### ISSUE TITLE
[Bug] Laser XT machines has a memory limit of 512 kb.

### ISSUE THREAD

**Issue by Fenix770** [OBattler/86Box#250]
Hello.

In recent builds, the memory limit of these machines was reduced from 1152 kb (640 kb conventional + 512 kb of EMS memory) to 512 kb of maximum  conventional memory
It could be interesting having a separate conventional and EMS memory configuration inthe emulation for Laser  XT machines to be closer to the real thing.

This particular machines has two different memory types (conventional and EMS) , they are not related one each other and the EMS memory does not backfill the conventional memory, like in many other systems.

PD: The memory configuration of these machines are written in their manuals and i read the pdf file of them.

Laser XT/3 8086 page 59
[ (http://www.minuszerodegrees.net/manuals/VTech/VTech%20Laser%20XT3%20-%20Operations%20Manual.pdf)
]
Laser Turbo XT 8088 page 51 (29 in the pdf file)
[http://www.minuszerodegrees.net/manuals/VTech/VTech%20-%20Laser%20Turbo%20XT%20-%20Operations%20Manual.pdf](url)
I explain why  in the the text forward. 

**The original harware and emulation** (It may be long but explains how different are from other machines)

Both of these machines had 512 kb of memory soldered to the mainboard and could be expanded to 640 kb of conventional memory, and 1 Mb of EMS. (However because of the difficulty to manage two EMS boards at the same time, only 512 kb EMS memory was added by Greatpsycho).
Altough using the 8086 model with 512 kb implies that two EMS board are active with 256kb in each one, because to fullfill the 16-bit bus the two 8-bit EMS boards must be active. 
This not behave as an 8-bit ISA EMS board, it rather uses 16-bit bus on 8086.

So can be two memory configurations for conventional memory and one or two for EMS memory in 86box/PCEM. 

In  8088/8086 512 kb or 640kb conventional plus 0/256/512 EMS on 8088 and 0/512kb EMS on 8086, because the different data  bus, 8-bit and 16-bit and 512kb  memory limit.

So to speak there are 6 different memory configurations for 8088 (2x3) and 4 for 8086 (2x2) in the emulation and  in real hardwre, 10 on 8088 (2x5) (with 768 kb and 1024kb) and 6 on 8086 (2x3) (with 1024kb EMS)

**Comment by OBattler** [comment]
They read the memory settings from the keyboard controller, and I couldn't get them to support more than 512 kB of RAM. In fact, the Laser Turbo XT BIOS we have seems to see *only* 512 kB, I can't even get it to 256 kB m ode, and the Laser XT/3 BIOS we have can be set to either 256 kB or 512 kB mode, depending on one bit in the keyboard controller.
The only thing I can imagine is, if they also read something from somewhere else, but without a datasheet, there's not much I can do.

**Comment by OBattler** [comment]
I am going to move these two machines to the Dev branch and then look into them after v2.00 has been released, because they are going to require finding datasheets and implementation of a lot of stuff.
