### ISSUE TITLE
Crash on startup: Access Violation (c0000005)

### ISSUE THREAD

**Issue by Insidious611** [OBattler/86Box#45]
I'm trying to run 86box on a very old machine (a 2007 MacBook to be precise) running Windows 7 x86. While I was able to get mainline PCem running, the minute I try to start 86box, I get a window for about 3 seconds and then before I can interact with anything it crashes with an access violation. I'm looking at other issue posts where people talk about getting a log, but I'm not sure how to get my copy of 86box to generate a log. Do I have to compile it myself in debug mode?

I'm using the 86box build #304 from polar.rol.im

**Comment by MoochMcGee** [comment]
In order to get a log from 86box, try running it from the command line as 86box > pclog.txt

**Comment by khang06** [comment]
Attempting to get 86box to log just freezes the program.
![image](https://cloud.githubusercontent.com/assets/11239786/23095103/5c4cfff6-f5d2-11e6-91b6-95904bb8a0ef.png)

**Comment by Wack0** [comment]
Does it generate any crash logs (*.dmp files)? If so can you provide those?
