### ISSUE TITLE
Makefiles hard-refer to automake-1.11. Makefiles should not pull in automake stuff *at all*, that's the whole point of using automake...

### ISSUE THREAD

**Issue by Insidious611** [OBattler/86Box#46]
I'm trying to put this diplomatically but your automake/autoconf system appears to be fundamentally broken. You're calling aclocal/autoconf/automake *from* the Makefile, when they should be run by autoconf when it generates the configure file, and should not be run at all during the make process, not least because someone might (and indeed, for many purposes, *should*) not have automake, autoconf, etc installed. Even if you want to go down this route, the fact you're hard-coding in automake-1.11 breaks systems such as mine which use automake-1.15, requiring manual adjusting of the Makefiles. I also don't quite understand what you're doing with depcomp, as retargeting it at automake-1.15's depcomp simply causes it to error out with "No command. Try depcomp --help for more information"

**Comment by Insidious611** [comment]
Also, relatedly, your "INSTALL" file appears to contain... a reference to automake's copy of install? Which is... very weird. INSTALL is not supposed to be a script, it's supposed to contain instructions on how to compile and install your project.

**Comment by MoochMcGee** [comment]
Sorry, this build system was originally designed by the mainline PCem dev,
Sarah Walker. Unfortunately, there's just not enough interest among the dev
team in Linux, so there's not enough interest in fixing this.

**Comment by Insidious611** [comment]
Ahh. amusingly enough I wasn't actually trying to compile *for* Linux, I
was trying to cross compile for Windows *using* Linux. But as far as build
systems go I suppose that's six in one hand half dozen in the other.

**Comment by MoochMcGee** [comment]
Well, for that, you need to cd src && make -f Makefile,mingw using a 32-bit
compiler.

**Comment by Enverex** [comment]
The odd thing is that PCEM does successfully build and install, 86Box doesn't. So either PCEM has been updated (and 86Box hasn't) or 86Box has somehow broken the build process.

**Comment by waltje** [comment]
The entire AutoMake stuff has been removed from 86Box.
