### ISSUE TITLE
Ne2000/Realtek Ethernet cards not working?

### ISSUE THREAD

**Issue by MrDude60** [OBattler/86Box#47]
Using WinPcap on both AMD/Intel platforms & both Win7/Win10, I cannot get LAN to work under Windows 95,98 & ME. I've even tried disabling/enabling Network bios. I'm using a wired Ethernet cable that attaches to my host PC with WinPcap installed (I'm NOT trying to get this to work over a wi-fi connection.) Can anyone else confirm this or is anyone able to get this to work with the latest 86Box build? If so, then how?

**Comment by MoochMcGee** [comment]
Try SLiRP lol

**Comment by MrDude60** [comment]
Okay, so do I need to install the third-party program SLiRP just like for [Win]Pcap or is it built in 86Box? Also, what's wrong with Pcap and why shouldn't I use it?

**Comment by MrDude60** [comment]
It now works over wi-fi, thanks!

LOL, the nice thing is I don't need to install winpcap and mess with adapters, meaning I don't need Admin rights! :)

**Comment by MoochMcGee** [comment]
Pcap's just harder to set up, that's all.
