### ISSUE TITLE
IDE (ATAPI) CD-ROM emulation not working correctly

### ISSUE THREAD

**Issue by MrDude60** [OBattler/86Box#52]
Using the Award 430VX PCI & 440FX PCI bios's, I can't get it to properly detect a cd-rom in the drive when booting from it or swapping it under windows guests. This is using both the ISO method and HOST CD-ROM drive method, and I am not using SCSI. It seems that the only scenario I can get to work with it is when using ISO method for trying to boot from a CD-ROM.

 I've tested this against PCem v11 and it all works fine. Therefore I'm assuming this is definitely a bug, correct?

**Comment by MrDude60** [comment]
Can anyone else confirm this please? It seems that Windows guests doesn't recognize CD-ROM's except when booting using the ISO method (IDE/ATAPI)

**Comment by MoochMcGee** [comment]
Is this still not working?

**Comment by MrDude60** [comment]
It can swap iso images within Win 98 now, so I guess so....

Thanks!
