### ISSUE TITLE
OPL3 problem

### ISSUE THREAD

**Issue by basic2004** [OBattler/86Box#69]
I heard better OPL3 than original PCem (maybe PCem doesn't use Nuked OPL3), setting Adlib Gold.  Some music player in PCem, loud clipping(popping?) noise from my speaker. but 86Box reduced this. Thanks!!

But 86Box has an incorrect OPL3 playing music with SB series and many OPL3 compatible soundcards like PCem now.
Only Adlib Gold plays correct OPL3.

I want correct OPL3 music and clean PCM sounds with SB series.
Let's fix this problem.

(edit) OPL3 in WSS playing correctly too.
PAS16 can't detect Adlib compatible.

**Comment by MoochMcGee** [comment]
Which apps and on which OSes have this problem? Can you record something
from both 86Box and real hardware?

**Comment by basic2004** [comment]
I don't have any actual dos pc. but I upload these comparision clips.
Recorded with 86Box, Adlib Gold and WSS in 86Box are almost same but SB16(maybe SBPro and AWE32 are same with SB16) isn't same with Adlib Gold.
Volume settings are different, sorry.

[compare-pm2bgm.zip](https://github.com/OBattler/86Box/files/680825/compare-pm2bgm.zip)
[compare-pm2bgm2.zip](https://github.com/OBattler/86Box/files/680829/compare-pm2bgm2.zip)

And I upload these sources and executable program.
[hts-pm2bgm.zip](https://github.com/OBattler/86Box/files/680839/hts-pm2bgm.zip)

**Comment by kazblox** [comment]
For the record, Nuked OPL3 is based off the complete OPL3 decaps. What you will experience will be different from real hardware ONLY because of the filters.

The problem you are experiencing though is a missing channel... Which is certainly odd. What are your IRQ/IO configurations for the SB16 on 86box? It could be likely that one of the I/O handlers is malfunctioning.

**Comment by basic2004** [comment]
SET BLASTER=A220 I5 D1 H5 P330 E620 T6
for AWE32 on my 86box. and except E620 on SB16.
Is this incorrect settings on 86Box?

**Comment by basic2004** [comment]
Now, SBProv2/16/AWE32 on 86Box detect OPL3 but recognize like OPL2, same as Adlib (not Gold)
- missing channel problem
- mono playback
- can't support 4op

**Comment by basic2004** [comment]
Finally, I solved.

in sound_sb.c
`        io_sethandler(0x0388, 0x0002, opl3_read,   NULL, NULL, opl3_write,   NULL, NULL, &sb->opl);`
to
`        io_sethandler(0x0388, 0x000**4**, opl3_read,   NULL, NULL, opl3_write,   NULL, NULL, &sb->opl);`
3 times (SB Pro V2, SB16, AWE32)

OPL3 playing correctly in SB Pro V2, SB16, AWE32 now.
