### ISSUE TITLE
Pentium emulation not working?

### ISSUE THREAD

**Issue by hashtagmarcopolo** [OBattler/86Box#9]
Hello,
I am using 86Box (64-bit version) on a Windows 10 64-bit laptop, and 486 emulation appears to be working just fine, but for whatever reason, no matter what Pentium motherboard I use, all I get is a screen that looks like this:

![86box pentium](https://cloud.githubusercontent.com/assets/21044104/17675701/c1b7b4c8-6322-11e6-9d8f-cd4f062d08e2.JPG)

Pentium II emulation works, why not Pentium 1? Does anyone know what could be causing this and maybe a possible solution?

**Comment by MoochMcGee** [comment]
Works for me m8.

**Comment by MoochMcGee** [comment]
Actually, I just noticed your problem. 64-bit 86Box is currently shit. Use 32-bit 86Box.

**Comment by hashtagmarcopolo** [comment]
Okay, thank you for that, will download it and see if it works.

**Comment by hashtagmarcopolo** [comment]
Nope, same screen. Have no idea what the problem could be.

**Comment by MoochMcGee** [comment]
Your BIOS is probably bad then.

**Comment by hashtagmarcopolo** [comment]
Strange, it works under normal PCem and PCem-X.
